name: colcon

on:
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  build:
    name: "${{ matrix.distribution }} (${{ matrix.ros }})"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - {distribution: ubuntu,    version: 22.04, ros: humble}
          - {distribution: ubuntu,    version: 24.04, ros: jazzy}
          - {distribution: almalinux, version: 8,     ros: humble}
          - {distribution: almalinux, version: 9,     ros: jazzy}

    continue-on-error: ${{ matrix.ros == 'rolling' }}

    container:
      image: ${{ matrix.distribution }}:${{ matrix.version }}

    steps:
      - name: install ROS 2
        uses: ros-tooling/setup-ros@v0.7

      - name: build and test dependencies (almalinux)
        if: ${{ matrix.distribution == 'almalinux'}}
        run: |
          dnf -y install libasan python3-mypy

      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: camera_ros
          target-ros2-distro: ${{ matrix.ros }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["asan-gcc", "tsan", "coverage-gcc", "memcheck"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/5d51dff38097e8c2bf46d7a5b804e65935aa7f47/index.yaml
